import type { ElementDefinition } from "./types";
import {
  TextIcon,
  TextareaIcon,
  NumberIcon,
  EmailIcon,
  PhoneIcon,
  PasswordIcon,
  UrlIcon,
  CheckboxIcon,
  RadioIcon,
  SelectIcon,
  DateIcon,
  TimeIcon,
  LocationIcon,
  FileIcon,
  H1Icon,
  H2Icon,
  H3Icon,
  DividerIcon,
  SpacerIcon,
  TableIcon,
} from "./icons";

export const fieldElements: ElementDefinition[] = [
  {
    type: "text",
    label: "Short text",
    icon: <TextIcon />,
    description: "Single line input",
    defaultProps: {
      label: "Text Field",
      placeholder: "Enter text...",
      required: false,
      width: "full",
    },
  },
  {
    type: "textarea",
    label: "Long text",
    icon: <TextareaIcon />,
    description: "Multi-line input",
    defaultProps: {
      label: "Message",
      placeholder: "Enter your message...",
      required: false,
      width: "full",
    },
  },
  {
    type: "number",
    label: "Number",
    icon: <NumberIcon />,
    description: "Only allows numbers",
    defaultProps: {
      label: "Number",
      placeholder: "0",
      required: false,
      width: "full",
    },
  },
  {
    type: "email",
    label: "Email",
    icon: <EmailIcon />,
    description: "Expects an email",
    defaultProps: {
      label: "Email Address",
      placeholder: "name@example.com",
      required: false,
      width: "full",
    },
  },
  {
    type: "phone",
    label: "Phone",
    icon: <PhoneIcon />,
    description: "Phone number input",
    defaultProps: {
      label: "Phone Number",
      placeholder: "+1 (555) 123-4567",
      required: false,
      width: "full",
    },
  },
  {
    type: "password",
    label: "Password",
    icon: <PasswordIcon />,
    description: "Hides characters",
    defaultProps: {
      label: "Password",
      placeholder: "Enter password...",
      required: false,
      width: "full",
    },
  },
  {
    type: "url",
    label: "URL",
    icon: <UrlIcon />,
    description: "Expects a URL",
    defaultProps: {
      label: "Website URL",
      placeholder: "https://example.com",
      required: false,
      width: "full",
    },
  },
  {
    type: "checkbox",
    label: "Multiple choice",
    icon: <CheckboxIcon />,
    description: "Accept multiple options",
    defaultProps: {
      label: "Select Options",
      options: ["Option 1", "Option 2", "Option 3"],
      required: false,
      width: "full",
    },
  },
  {
    type: "radio",
    label: "Single choice",
    icon: <RadioIcon />,
    description: "Accept a single option",
    defaultProps: {
      label: "Choose One",
      options: ["Option A", "Option B", "Option C"],
      required: false,
      width: "full",
    },
  },
  {
    type: "select",
    label: "Dropdown",
    icon: <SelectIcon />,
    description: "Select input",
    defaultProps: {
      label: "Select Option",
      options: ["Option 1", "Option 2", "Option 3"],
      required: false,
      width: "full",
    },
  },
  {
    type: "date",
    label: "Date",
    icon: <DateIcon />,
    description: "Datepicker input",
    defaultProps: {
      label: "Date",
      required: false,
      width: "full",
    },
  },
  {
    type: "time",
    label: "Time",
    icon: <TimeIcon />,
    description: "Time picker input",
    defaultProps: {
      label: "Time",
      required: false,
      width: "full",
    },
  },
  {
    type: "location",
    label: "Location",
    icon: <LocationIcon />,
    description: "Location input",
    defaultProps: {
      label: "Location",
      placeholder: "Enter location...",
      required: false,
      width: "full",
    },
  },
  {
    type: "file",
    label: "File Upload",
    icon: <FileIcon />,
    description: "File Upload input",
    defaultProps: {
      label: "Upload File",
      helper: "Max file size: 10MB",
      required: false,
      width: "full",
    },
  },
];

export const pageElements: ElementDefinition[] = [
  {
    type: "h1",
    label: "Form heading (H1)",
    icon: <H1Icon />,
    description: "Heading for form",
    defaultProps: {
      label: "Form Heading",
      placeholder: "Enter form title...",
      width: "full",
    },
  },
  {
    type: "h2",
    label: "Section heading (H2)",
    icon: <H2Icon />,
    description: "Heading for sections",
    defaultProps: {
      label: "Section Heading",
      placeholder: "Enter section title...",
      width: "full",
    },
  },
  {
    type: "h3",
    label: "Subheading (H3)",
    icon: <H3Icon />,
    description: "Heading for subsections",
    defaultProps: {
      label: "Subheading",
      placeholder: "Enter subsection title...",
      width: "full",
    },
  },
  {
    type: "divider",
    label: "Divider",
    icon: <DividerIcon />,
    description: "Visual separation",
    defaultProps: {
      label: "Divider",
      width: "full",
    },
  },
  {
    type: "spacer",
    label: "Spacer",
    icon: <SpacerIcon />,
    description: "Empty space",
    defaultProps: {
      label: "Spacer",
      width: "full",
    },
  },
  {
    type: "table",
    label: "Table",
    icon: <TableIcon />,
    description: "Rows and columns",
    defaultProps: {
      label: "Table",
      helper: "Organize data in rows and columns",
      width: "full",
    },
  },
];
